
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminPanel = new javax.swing.JLabel();
        AdminDoctor = new javax.swing.JButton();
        AdminBack = new javax.swing.JButton();
        AdminExit = new javax.swing.JButton();
        AdminNurse = new javax.swing.JButton();
        AdminReceptionist = new javax.swing.JButton();
        AdminPatient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminPanel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        AdminPanel.setForeground(new java.awt.Color(102, 102, 255));
        AdminPanel.setText("ADMIN PANEL");

        AdminDoctor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AdminDoctor.setText("Doctor");
        AdminDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminDoctorActionPerformed(evt);
            }
        });

        AdminBack.setText("Back");
        AdminBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBackActionPerformed(evt);
            }
        });

        AdminExit.setText("EXIT");
        AdminExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminExitActionPerformed(evt);
            }
        });

        AdminNurse.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AdminNurse.setText("Nurse");
        AdminNurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminNurseActionPerformed(evt);
            }
        });

        AdminReceptionist.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AdminReceptionist.setText("Receptionist");
        AdminReceptionist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminReceptionistActionPerformed(evt);
            }
        });

        AdminPatient.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AdminPatient.setText("Patient");
        AdminPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminPatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(AdminBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminExit)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(AdminPanel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AdminPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminNurse, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminReceptionist))))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(AdminPanel)
                .addGap(52, 52, 52)
                .addComponent(AdminDoctor)
                .addGap(48, 48, 48)
                .addComponent(AdminPatient)
                .addGap(46, 46, 46)
                .addComponent(AdminNurse)
                .addGap(49, 49, 49)
                .addComponent(AdminReceptionist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AdminBack)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AdminExit)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminDoctorActionPerformed

        Doctor  d =new Doctor();
        d.setVisible(true);
        d.pack();
        d.setLocationRelativeTo(null);
        d.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_AdminDoctorActionPerformed

    private void AdminBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBackActionPerformed
        // TODO add your handling code here:
        login lg=new login();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_AdminBackActionPerformed

    private void AdminExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_AdminExitActionPerformed

    private void AdminNurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminNurseActionPerformed
         Nurse  n =new Nurse();
        n.setVisible(true);
        n.pack();
        n.setLocationRelativeTo(null);
        n.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_AdminNurseActionPerformed

    private void AdminReceptionistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminReceptionistActionPerformed
         Receptionist  r =new Receptionist();
        r.setVisible(true);
        r.pack();
        r.setLocationRelativeTo(null);
        r.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_AdminReceptionistActionPerformed

    private void AdminPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminPatientActionPerformed
        Patient  p =new Patient();
        p.setVisible(true);
        p.pack();
        p.setLocationRelativeTo(null);
        p.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_AdminPatientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBack;
    private javax.swing.JButton AdminDoctor;
    private javax.swing.JButton AdminExit;
    private javax.swing.JButton AdminNurse;
    private javax.swing.JLabel AdminPanel;
    private javax.swing.JButton AdminPatient;
    private javax.swing.JButton AdminReceptionist;
    // End of variables declaration//GEN-END:variables
}
