
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Receptionist extends javax.swing.JFrame {

    Connection con= null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public Receptionist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rname = new javax.swing.JTextField();
        rsearch = new javax.swing.JButton();
        jLabelrage = new javax.swing.JLabel();
        rage = new javax.swing.JTextField();
        jaddr = new javax.swing.JButton();
        jremover = new javax.swing.JButton();
        jupdater = new javax.swing.JButton();
        jLabelrdesig = new javax.swing.JLabel();
        rdesig = new javax.swing.JTextField();
        jLabersal = new javax.swing.JLabel();
        rsal = new javax.swing.JTextField();
        jLabelruname = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelrname = new javax.swing.JLabel();
        jLabelrid = new javax.swing.JLabel();
        rid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rsearch.setText("Search");
        rsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsearchActionPerformed(evt);
            }
        });

        jLabelrage.setText("Receptionist_Age:");

        jaddr.setText("Add ");
        jaddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddrActionPerformed(evt);
            }
        });

        jremover.setText("Remove ");
        jremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jremoverActionPerformed(evt);
            }
        });

        jupdater.setText("Update");
        jupdater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdaterActionPerformed(evt);
            }
        });

        jLabelrdesig.setText("Receptionist_Designation:");

        jLabersal.setText("Salary:");

        jLabelruname.setText("Receptionist_Username:");

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 204));
        jLabel1.setText("Receptionist Details");

        jLabelrname.setText("Receptionist_Name:");

        jLabelrid.setText("Receptionist_ID:");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(480, 480, 480))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelrid)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelrage)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rage, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rid, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelrname)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                        .addComponent(rname, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(90, 90, 90)
                                            .addComponent(jLabelruname)
                                            .addGap(18, 18, 18)
                                            .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(31, 31, 31)
                                            .addComponent(jLabersal)
                                            .addGap(18, 18, 18)
                                            .addComponent(rsal, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(jLabelrdesig)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdesig, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 171, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jupdater, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jremover, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 171, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rsearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jaddr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelrid)
                            .addComponent(rid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelrname)
                                    .addComponent(rname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelrage)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabersal)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelruname)
                            .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelrdesig)
                            .addComponent(rdesig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(rsearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jaddr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jremover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jupdater)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 342, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsearchActionPerformed

        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","DIN","password");

            String sql="select * from RECEPTIONIST where Receptionist_ID=?";

            PreparedStatement stat=con.prepareStatement(sql);
            stat.setInt(1,Integer.parseInt(rid.getText()));
            ResultSet rs=stat.executeQuery();
            if(rs.next())
            {
                rid.setText(rs.getString("Receptionist_ID"));
                rname.setText(rs.getString("Receptionist_Name"));
                rage.setText(rs.getString("Receptionist_Age"));
                
                uname.setText(rs.getString("Receptionist_Username"));
                rdesig.setText(rs.getString("Receptionist_Designation"));
                rsal.setText(rs.getString("Salary"));
                

            }
            else{

                JOptionPane.showMessageDialog(null, "Not Found");
            }

            con.close();
        }

        catch(Exception e){

            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_rsearchActionPerformed

    private void jaddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddrActionPerformed

        try {

            String Receptionist_Name,Receptionist_Username,Receptionist_Designation;
            int Receptionist_Age,Salary;

            int Receptionist_ID;
            Receptionist_ID = Integer.parseInt(rid.getText());
            Receptionist_Name = rname.getText();

            Receptionist_Age = Integer.parseInt(rage.getText());
           

            Receptionist_Username=uname.getText();
            Receptionist_Designation=rdesig.getText();
            Salary=Integer.parseInt(rsal.getText());
            

            //insert query
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","DIN","password");

            PreparedStatement pst;
            String sql ="INSERT INTO RECEPTIONIST (Receptionist_ID,Receptionist_Name,Receptionist_Age,Receptionist_Username,Receptionist_Designation,Salary )" +"  values (? , ?, ? ,?,?,? )";
            pst = con.prepareStatement(sql);
            pst.setInt(1,Receptionist_ID);
            pst.setString(2,Receptionist_Name);

            pst.setInt(3, Receptionist_Age);
            

            pst.setString(4, Receptionist_Username);
            pst.setString(5, Receptionist_Designation);
            pst.setInt(6, Salary);
            JOptionPane.showMessageDialog (null," Added Successfully");

            if (rid.getText().isEmpty()){

                System.out.println("Plz Fill up blanks");

            }
            else if (rname.getText().isEmpty()){
                System.out.println("Plz Fill up blanks");
            }

            else if (rage.getText().isEmpty()){
                System.out.println("Plz Fill up blanks");
            }
            

            else if (uname.getText().isEmpty()){
                System.out.println("Plz Fill up blanks");
            }
            else if (rdesig.getText().isEmpty()){
                System.out.println("Plz Fill up blanks");
            }
            else if (rsal.getText().isEmpty()){
                System.out.println("Plz Fill up blanks");
            }
           

            else {
                pst.execute();
               
                con.close();
            }

        } catch(Exception ex) {

            JOptionPane.showMessageDialog(null, ex);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jaddrActionPerformed
       public static void ReceptionistTrigger (int Receptionist_ID,String Receptionist_Name,int Receptionist_Age,String Receptionist_Username,String Receptionist_Designation,int Salary)
                                                        throws SQLException
  {
    Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","DIN","password");
    String sql = "{call Restricted_Insert_RECEPTIONIST}";
    try
    {
        
        
     PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setInt(1,Receptionist_ID);
            pst.setString(2,Receptionist_Name);
        
            pst.setInt(3, Receptionist_Age);
            pst.setString(4, Receptionist_Username);
          
            pst.setString(5, Receptionist_Designation);
          
            
            pst.setInt(6, Salary);
            
           
    }
    catch (SQLException e)
    {
      System.err.println(e.getMessage());
    }
  }
    
    
    
    
    private void jremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jremoverActionPerformed

        try{
            //Connection conn;
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","DIN","password");
            String sql="delete from RECEPTIONIST  where Receptionist_ID=?";
            PreparedStatement stat=con.prepareStatement(sql);

            stat.setInt(1,Integer.parseInt(rid.getText()) );
            stat.executeUpdate();
            JOptionPane.showMessageDialog (null," Deleted Successfully");
            con.close();

            rid.setText(" ");
            rname.setText(" ");

            rage.setText(" ");
            

            uname.setText(" ");
            rdesig.setText(" ");
            rsal.setText(" ");
            

        }

        catch(Exception e)

        {

            JOptionPane.showMessageDialog (null,"Something is Wrong.Please check again.");

        }
    }//GEN-LAST:event_jremoverActionPerformed

    private void jupdaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdaterActionPerformed

        try{

             String Receptionist_Name,Receptionist_Username,Receptionist_Designation;
            int Receptionist_Age,Salary;

            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","DIN","password");
           
            int Receptionist_ID;
            Receptionist_ID = Integer.parseInt(rid.getText());
            Receptionist_Name = rname.getText();

            Receptionist_Age = Integer.parseInt(rage.getText());
            

            Receptionist_Username=uname.getText();
            Receptionist_Designation=rdesig.getText();
            Salary=Integer.parseInt(rsal.getText());
            

            String sq1 = "update RECEPTIONIST set Receptionist_ID='"+Receptionist_ID+"', Receptionist_Name='"+Receptionist_Name+"',Receptionist_Age='"+Receptionist_Age+"',Receptionist_Username='"+Receptionist_Username+"',Receptionist_Designation='"+Receptionist_Designation+"',Salary='"+Salary+"' where Receptionist_ID='"+Receptionist_ID+"'";
            //PreparedStatement pst;
            pst=con.prepareStatement(sq1);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Updated Successfully");
            //this.jdisplayr.enable();
            // conn.close();

        }

        catch(  Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,ex);
    }//GEN-LAST:event_jupdaterActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Admin rg=new Admin();
        rg.setVisible(true);
        rg.pack();
        rg.setLocationRelativeTo(null);
        rg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receptionist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelrage;
    private javax.swing.JLabel jLabelrdesig;
    private javax.swing.JLabel jLabelrid;
    private javax.swing.JLabel jLabelrname;
    private javax.swing.JLabel jLabelruname;
    private javax.swing.JLabel jLabersal;
    private javax.swing.JButton jaddr;
    private javax.swing.JButton jremover;
    private javax.swing.JButton jupdater;
    private javax.swing.JTextField rage;
    private javax.swing.JTextField rdesig;
    private javax.swing.JTextField rid;
    private javax.swing.JTextField rname;
    private javax.swing.JTextField rsal;
    private javax.swing.JButton rsearch;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
